"""EDA v2 — proper parsing (sep=';', decimal=','), full structural overview."""
import pandas as pd

CSV = r"C:\Users\tmiha\Documents\Touchpulse\Assignment\Database - Testcase_agentic_ai_V1.0.zip.csv"

df = pd.read_csv(CSV, sep=";", decimal=",", dayfirst=True, parse_dates=["time"])

print("=" * 70)
print("SHAPE:", df.shape)
print("=" * 70)
print("DTYPES:")
print(df.dtypes)
print("=" * 70)
print("HEAD:")
print(df.head().to_string())
print("=" * 70)
print("TAIL:")
print(df.tail().to_string())
print("=" * 70)
print("MISSING per column:")
print(df.isna().sum())
print("=" * 70)
print("DUPLICATE ROWS:", df.duplicated().sum())
print("=" * 70)
print("UNIQUE COUNTS:")
for c in df.columns:
    print(f"  {c}: {df[c].nunique()}")
print("=" * 70)
print("DESCRIBE (numeric):")
print(df.describe(include="number").to_string())
print("=" * 70)
print("DESCRIBE (object):")
print(df.describe(include=["object"]).to_string())
print("=" * 70)
print("TIME RANGE:", df["time"].min(), "->", df["time"].max())
print("DAYS COVERED:", (df["time"].max() - df["time"].min()).days)
print("=" * 70)
print("METRIC IDs (top 30):")
print(df["MetricId"].value_counts().head(30).to_string())
print("=" * 70)
print("IPC value counts (top 20):")
print(df["IPC"].value_counts().head(20).to_string())
print("=" * 70)
print("Data Factory value counts:")
print(df["Data Factory"].value_counts().to_string())
print("=" * 70)
print("CpuMHz value counts:")
print(df["CpuMHz"].value_counts().to_string())
